import { Category, Product, Review } from "@/types";

// ─── Categories ───────────────────────────────────────────────────────────────
export const categories: Category[] = [
  {
    id: "1",
    name: "Cute Plush Ornaments without Bell",
    slug: "cute-plush-ornaments-without-bell",
    description: "Soft plush felt animals & cute ornaments hand-stitched without bells",
    image: "/images/products/felt-sleeping-bear.jpg",
    product_count: 3,
    color: "bg-brand-pink-light",
  },
  {
    id: "2",
    name: "Cute Plush Ornaments with Bell",
    slug: "cute-plush-ornaments-with-bell",
    description: "Charming plush felt ornaments featuring gentle chiming ghungroo bells",
    image: "/images/products/felt-birds-mobile.jpg",
    product_count: 2,
    color: "bg-brand-lavender",
  },
  {
    id: "3",
    name: "Door and Wall Decor",
    slug: "door-and-wall-decor",
    description: "Whimsical hand-stitched felt branch hangings, torans, and wall art",
    image: "/images/products/owl-branch-hanging.jpg",
    product_count: 4,
    color: "bg-brand-green-light",
  },
  {
    id: "4",
    name: "Festive Special Decor",
    slug: "festive-special-decor",
    description: "Vibrant handcrafted felt Diyas, tassels, torans & festive celebration accents",
    image: "/images/products/diya-hanging-tassels.jpg",
    product_count: 3,
    color: "bg-brand-terracotta-light",
  },
  {
    id: "5",
    name: "Garden Decor",
    slug: "garden-decor",
    description: "Enchanting nature-inspired felt birds, flowers, and outdoor balcony hangings",
    image: "/images/products/diya-hanging-bells.jpg",
    product_count: 2,
    color: "bg-brand-yellow",
  },
  {
    id: "6",
    name: "Personalised Name",
    slug: "personalised-name",
    description: "Handcrafted felt creations with custom names, initials, and personalized colors",
    image: "/images/products/owl-branch-hanging.jpg",
    product_count: 4,
    color: "bg-brand-pink-light",
  },
];

// ─── Products ─────────────────────────────────────────────────────────────────
export const products: Product[] = [
  {
    id: "1",
    name: "Handcrafted Festive Diya Bell Hanging",
    slug: "handcrafted-festive-diya-bell-hanging",
    description:
      "Brighten your home with this exquisite handcrafted felt Diya hanging ornament. Featuring a bright lime-green felt diya base, flame motif, hand-sewn leaf appliques, colorful bead strands, and traditional brass ghungroo bells that create a gentle musical chime. Hand-stitched with love, making it a perfect piece for Diwali, Puja rooms, entrance doors, and festive gifting.",
    short_description: "Vibrant felt Diya ornament with embroidered leaves, beads & brass ghungroo bells",
    price: 499,
    compare_price: 699,
    images: [
      "/images/products/diya-hanging-bells.jpg",
    ],
    category: categories[3],
    category_id: "4",
    stock: 15,
    is_featured: true,
    is_new: true,
    is_bestseller: true,
    tags: ["festive", "diya", "diwali", "puja decor", "handmade", "bells", "toran"],
    rating: 4.9,
    review_count: 28,
    sku: "PHA-FES-001",
    weight: "150g",
    materials: ["Premium Wool Felt", "Wooden & Glass Beads", "Brass Ghungroo Bells", "Embroidery Thread"],
    colors: ["Lime Green & Orange", "Multicolor"],
    customizable: true,
    created_at: "2024-01-15",
  },
  {
    id: "2",
    name: "Royal Magenta Diya Fringe Wall Hanging",
    slug: "royal-magenta-diya-fringe-wall-hanging",
    description:
      "A stunning festive accent crafted from premium magenta felt with delicate stitch work and leaf embroidery. Features a long, lush green tassel fringe accented with cascading brass ghungroo bells that add grace and movement to your doorways, balconies, or living space during auspicious celebrations.",
    short_description: "Elegantly crafted magenta felt Diya with green tassel fringe & cascading brass bells",
    price: 549,
    compare_price: 749,
    images: [
      "/images/products/diya-hanging-tassels.jpg",
    ],
    category: categories[3],
    category_id: "4",
    stock: 12,
    is_featured: true,
    is_new: false,
    is_bestseller: false,
    tags: ["diya", "tassel", "festive decor", "wall hanging", "handmade", "diwali"],
    rating: 4.8,
    review_count: 19,
    sku: "PHA-FES-002",
    weight: "180g",
    materials: ["Premium Wool Felt", "Silk Thread Fringe", "Brass Ghungroo Bells"],
    colors: ["Magenta & Green", "Golden Flame"],
    customizable: true,
    created_at: "2024-01-20",
  },
  {
    id: "3",
    name: "Three Wise Owls Felt Branch Wall Hanging",
    slug: "three-wise-owls-felt-branch-wall-hanging",
    description:
      "Bring warmth and playful charm to your walls with this detailed owl branch hanging. Three adorable felt owls in vibrant pink, blue, and orange hues perch on a soft stuffed green branch detailed with sparkling yellow flowers and trailing beaded strings with chime bells. Each owl is meticulously stitched with button accents and sequin embellishments.",
    short_description: "Handcrafted tree branch featuring 3 colorful embroidered felt owls with yellow flowers & chime bells",
    price: 899,
    compare_price: 1199,
    images: [
      "/images/products/owl-branch-hanging.jpg",
    ],
    category: categories[2],
    category_id: "3",
    stock: 8,
    is_featured: true,
    is_new: true,
    is_bestseller: true,
    tags: ["owl decor", "branch hanging", "wall art", "handmade", "chime bells"],
    rating: 5.0,
    review_count: 34,
    sku: "PHA-WAL-001",
    weight: "250g",
    materials: ["Hand-stitched Wool Felt", "Decorative Buttons & Sequins", "Wooden Beads", "Brass Bells"],
    colors: ["Multicolor Owls", "Forest Green Branch"],
    customizable: true,
    created_at: "2024-02-01",
  },
  {
    id: "4",
    name: "Cozy Paws Felt Sleeping Bear Plush",
    slug: "cozy-paws-felt-sleeping-bear-plush",
    description:
      "Fall in love with this adorable sleeping bear, lovingly hand-stitched with visible contrast blanket embroidery stitches. Crafted from soft cream felt, wearing stylish black overalls with pocket detail and a purple neck scarf. Perfect as a nursery accent, bag charm, tree ornament, or thoughtful handmade gift.",
    short_description: "Hand-stitched felt teddy bear wearing cute black overalls and a purple scarf",
    price: 399,
    compare_price: 499,
    images: [
      "/images/products/felt-sleeping-bear.jpg",
    ],
    category: categories[0],
    category_id: "1",
    stock: 20,
    is_featured: true,
    is_new: false,
    is_bestseller: true,
    tags: ["teddy bear", "nursery ornament", "plush", "handmade", "gift"],
    rating: 4.9,
    review_count: 42,
    sku: "PHA-PLU-001",
    weight: "110g",
    materials: ["Hypoallergenic Wool Felt", "Polyfill Cotton", "Embroidery Floss"],
    colors: ["Cream & Black", "Purple Scarf"],
    customizable: false,
    created_at: "2024-02-10",
  },
  {
    id: "5",
    name: "Enchanted Birds & Branch Hanging Mobile",
    slug: "enchanted-birds-branch-hanging-mobile",
    description:
      "Transform any room into a vibrant paradise with this showstopping felt birds hanging mobile. Features 4 brightly colored songbirds perched atop a hand-sculpted green branch adorned with blossoms, with 6 charming suspended birds swaying gently below. Hand-stitched with vibrant felt art details, making it a dream piece for living rooms, entrance doorways, or baby nurseries.",
    short_description: "Spectacular handcrafted felt mobile with 10 colorful birds perched & suspended on a green branch",
    price: 1299,
    compare_price: 1699,
    images: [
      "/images/products/felt-birds-mobile.jpg",
    ],
    category: categories[4],
    category_id: "5",
    stock: 6,
    is_featured: true,
    is_new: true,
    is_bestseller: true,
    tags: ["bird mobile", "nursery decor", "hanging mobile", "handcrafted art", "statement piece"],
    rating: 5.0,
    review_count: 56,
    sku: "PHA-NUR-001",
    weight: "320g",
    materials: ["Premium Colorfast Felt", "Soft Fiber Fill", "Strong Cotton Cord", "Button Details"],
    colors: ["Multicolor Songbirds", "Deep Green Branch"],
    customizable: true,
    created_at: "2024-02-15",
  },
];

export const testimonials: Review[] = [
  {
    id: "r1",
    product_id: "1",
    user_id: "u1",
    user_name: "Arjun Sharma",
    user_avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&q=80",
    rating: 5,
    comment:
      "Bahut accha product hai. I was initially unsure about ordering handmade décor online, but the quality genuinely impressed me. Stitching is neat, the colours are beautiful and the product feels quite sturdy. Easily washable bhi hai, which is a big plus.",
    created_at: "2024-03-10",
    verified: true,
  },
  {
    id: "r2",
    product_id: "2",
    user_id: "u2",
    user_name: "Karan Mehta",
    user_avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&q=80",
    rating: 5,
    comment:
      "Bought this for my niece’s room and she absolutely loved it. The material feels soft and safe, with no sharp edges or anything that could hurt a child. It looks beautiful and the finishing is very good. Definitely a better choice than plastic décor.",
    created_at: "2024-03-05",
    verified: true,
  },
  {
    id: "r3",
    product_id: "3",
    user_id: "u3",
    user_name: "Simran Kapoor",
    user_avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&q=80",
    rating: 5,
    comment:
      "Halloween décor usually means plastic decorations, so I wanted something different this year. This handmade felt piece looked absolutely adorable and gave our home a cosy festive vibe without looking too over-the-top. It’s lightweight, reusable and easy to clean, so I can bring it out every Halloween. Such a cute and sustainable alternative!",
    created_at: "2024-02-28",
    verified: true,
  },
  {
    id: "r4",
    product_id: "4",
    user_id: "u4",
    user_name: "Kavya Singh",
    user_avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&q=80",
    rating: 5,
    comment:
      "बहुत प्यारा और खूबसूरत handmade décor है। ❤️ Finishing देखकर साफ पता चलता है कि इसे बहुत ध्यान से बनाया गया है। Wash करने के बाद भी इसका shape और colours अच्छे रहे। I really appreciate that it is reusable and made to last instead of being disposable décor.",
    created_at: "2024-02-20",
    verified: true,
  },
  {
    id: "r5",
    product_id: "5",
    user_id: "u5",
    user_name: "Neha Agarwal",
    user_avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&q=80",
    rating: 5,
    comment:
      "I gifted this to my sister for her new home and she absolutely loved it! ❤️ The handmade detailing is beautiful and it makes the room look so warm and elegant. Quality bhi kaafi achhi hai, stitching is strong and the product feels very durable. A perfect handmade gift.",
    created_at: "2024-02-14",
    verified: true,
  },
  {
    id: "r6",
    product_id: "1",
    user_id: "u6",
    user_name: "Riya Mehta",
    user_avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&q=80",
    rating: 5,
    comment:
      "Bahut hi sundar aur neatly made hai! Colours exactly pictures jaise hain. Sabse achhi baat hai ki washable hai, so kids ke room mein use karne mein tension nahi hoti. It feels safe, soft and thoughtfully made. Definitely a beautiful addition to our home.",
    created_at: "2024-02-08",
    verified: true,
  },
  {
    id: "r7",
    product_id: "2",
    user_id: "u7",
    user_name: "Vivek Joshi",
    user_avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&q=80",
    rating: 5,
    comment:
      "A really beautiful piece of sustainable décor. Mujhe sabse achhi baat ye lagi ki it is completely handmade and doesn’t look like typical factory-made decoration. The stitching and finishing are excellent, and being washable makes maintenance very easy. Worth buying!",
    created_at: "2024-01-30",
    verified: true,
  },
  {
    id: "r8",
    product_id: "3",
    user_id: "u8",
    user_name: "Rohan Gupta",
    user_avatar: "",
    rating: 5,
    comment:
      "The product is beautifully made and surprisingly durable. I’ve had it hanging in my living room for months and it still looks as good as new. It adds a very warm and handcrafted feel to the space. Would definitely recommend it for gifting.",
    created_at: "2024-01-25",
    verified: true,
  },
  {
    id: "r9",
    product_id: "4",
    user_id: "u9",
    user_name: "Aditya Kapoor",
    user_avatar: "",
    rating: 5,
    comment:
      "Maine ye Diwali gifting ke liye order kiya tha and everyone appreciated it. The handmade detailing gives it a very premium and personal feel. Plus, it can be reused every year, so it’s much more meaningful than disposable decorations. Great product!",
    created_at: "2024-01-18",
    verified: true,
  },
];

// ─── Instagram Gallery ────────────────────────────────────────────────────────
export const instagramImages = [
  "/images/products/diya-hanging-bells.jpg",
  "/images/products/diya-hanging-tassels.jpg",
  "/images/products/owl-branch-hanging.jpg",
  "/images/products/felt-sleeping-bear.jpg",
  "/images/products/felt-birds-mobile.jpg",
  "/images/products/owl-branch-hanging.jpg",
];

// Helpers
export const getFeaturedProducts = () => products.filter((p) => p.is_featured);
export const getBestSellers = () => products.filter((p) => p.is_bestseller);
export const getNewArrivals = () => products.filter((p) => p.is_new);
export const getProductBySlug = (slug: string) =>
  products.find((p) => p.slug === slug);
export const getProductsByCategory = (categorySlug: string) =>
  products.filter((p) => p.category.slug === categorySlug);
