import { Category, Product, Review } from "@/types";

// ─── Categories ───────────────────────────────────────────────────────────────
export const categories: Category[] = [
  {
    id: "1",
    name: "Nursery Décor",
    slug: "nursery-decor",
    description: "Adorable handcrafted pieces for your little one's room",
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&q=80",
    product_count: 2,
    color: "bg-brand-pink-light",
  },
  {
    id: "2",
    name: "Festive Decorations",
    slug: "festive-decorations",
    description: "Bring joy and color to every celebration",
    image: "https://images.unsplash.com/photo-1576919228236-a097c32a5cd4?w=600&q=80",
    product_count: 3,
    color: "bg-brand-green-light",
  },
  {
    id: "3",
    name: "Home Décor",
    slug: "home-decor",
    description: "Handcrafted art to warm up your living spaces",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&q=80",
    product_count: 2,
    color: "bg-brand-terracotta-light",
  },
  {
    id: "4",
    name: "Gifts & Hampers",
    slug: "gifts-hampers",
    description: "Unique handmade gifts for every occasion",
    image: "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=600&q=80",
    product_count: 2,
    color: "bg-brand-lavender",
  },
  {
    id: "5",
    name: "Wall Art",
    slug: "wall-art",
    description: "Felt wall art to express your unique style",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    product_count: 2,
    color: "bg-brand-yellow",
  },
  {
    id: "6",
    name: "Keychains & Accessories",
    slug: "keychains-accessories",
    description: "Cute felt accessories for everyday carry",
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80",
    product_count: 2,
    color: "bg-brand-cream-dark",
  },
];

// ─── Products ─────────────────────────────────────────────────────────────────
export const products: Product[] = [
  {
    id: "1",
    name: "Felt Rainbow Mobile",
    slug: "felt-rainbow-mobile",
    description:
      "A dreamy hand-stitched rainbow mobile crafted from premium wool felt, filled with soft fiber cotton. Each rainbow arch is carefully cut and stitched by hand, creating a whimsical nursery decoration that brings joy to your little one. Perfect as a baby shower gift or nursery accent.",
    short_description: "Hand-stitched rainbow mobile for nursery décor",
    price: 899,
    compare_price: 1199,
    images: [
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80",
      "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=800&q=80",
      "https://images.unsplash.com/photo-1545173168-9f1947eebb7f?w=800&q=80",
    ],
    category: categories[0],
    category_id: "1",
    stock: 12,
    is_featured: true,
    is_new: false,
    is_bestseller: true,
    tags: ["nursery", "mobile", "rainbow", "handmade"],
    rating: 4.9,
    review_count: 47,
    sku: "PHA-NUR-001",
    weight: "200g",
    materials: ["Premium Wool Felt", "Fiber Cotton", "Cotton Thread"],
    colors: ["Pastel Rainbow", "Blush Pink", "Sage Green"],
    customizable: true,
    created_at: "2024-01-15",
  },
  {
    id: "2",
    name: "Felt Flower Garland",
    slug: "felt-flower-garland",
    description:
      "A beautiful hand-stitched felt flower garland perfect for room décor, parties, or weddings. Each flower is individually crafted using premium felt fabric and lightly stuffed with cotton for a 3D effect. Available in custom color combinations.",
    short_description: "Handcrafted felt flower garland for any occasion",
    price: 649,
    compare_price: 849,
    images: [
      "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&q=80",
      "https://images.unsplash.com/photo-1519378058457-4c29a0a2efac?w=800&q=80",
    ],
    category: categories[1],
    category_id: "2",
    stock: 20,
    is_featured: true,
    is_new: true,
    is_bestseller: false,
    tags: ["garland", "flowers", "festive", "party"],
    rating: 4.8,
    review_count: 32,
    sku: "PHA-FES-001",
    weight: "150g",
    materials: ["Premium Felt", "Fiber Cotton"],
    colors: ["Blush & Sage", "Pastel Mix", "Terracotta & Cream"],
    customizable: true,
    created_at: "2024-02-10",
  },
  {
    id: "3",
    name: "Felt Cloud Wall Art",
    slug: "felt-cloud-wall-art",
    description:
      "Charming hand-stitched cloud wall art set featuring fluffy clouds with rainbow accents. Made from premium wool felt, each cloud is stuffed with soft fiber cotton for a plush, dimensional look. Set of 3 clouds in graduating sizes.",
    short_description: "Set of 3 plush felt cloud decorations for walls",
    price: 1199,
    compare_price: undefined,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    ],
    category: categories[4],
    category_id: "5",
    stock: 8,
    is_featured: true,
    is_new: true,
    is_bestseller: false,
    tags: ["wall art", "clouds", "nursery", "3D"],
    rating: 5.0,
    review_count: 18,
    sku: "PHA-WAL-001",
    weight: "350g",
    materials: ["Wool Felt", "Fiber Cotton"],
    colors: ["White & Rainbow", "Blush & Cream"],
    customizable: false,
    created_at: "2024-03-05",
  },
  {
    id: "4",
    name: "Felt Cactus Plushie",
    slug: "felt-cactus-plushie",
    description:
      "Adorable hand-stitched cactus plushie that doesn't prick! Made from premium green felt with colorful flower accents, each cactus is stuffed with soft fiber cotton. Perfect for desks, shelves, or as a quirky gift.",
    short_description: "Cute handmade felt cactus stuffed toy",
    price: 499,
    compare_price: 649,
    images: [
      "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&q=80",
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80",
    ],
    category: categories[2],
    category_id: "3",
    stock: 25,
    is_featured: false,
    is_new: false,
    is_bestseller: true,
    tags: ["cactus", "plushie", "desk decor", "gift"],
    rating: 4.7,
    review_count: 63,
    sku: "PHA-HOM-001",
    weight: "180g",
    materials: ["Premium Felt", "Fiber Cotton"],
    colors: ["Sage Green", "Dark Green", "Mint"],
    customizable: true,
    created_at: "2023-11-20",
  },
  {
    id: "5",
    name: "Diwali Felt Diya Set",
    slug: "diwali-felt-diya-set",
    description:
      "Celebrate Diwali with these exquisite hand-stitched felt diyas. Each diya is embroidered with traditional patterns and shimmers with golden thread. Set of 5 diyas in festive colors, perfect for gifting or home décor during festivities.",
    short_description: "Handcrafted felt diya set for Diwali décor",
    price: 749,
    compare_price: 999,
    images: [
      "https://images.unsplash.com/photo-1574265094229-9a11f1e3699c?w=800&q=80",
      "https://images.unsplash.com/photo-1592609931095-54a2168ae893?w=800&q=80",
    ],
    category: categories[1],
    category_id: "2",
    stock: 30,
    is_featured: true,
    is_new: false,
    is_bestseller: true,
    tags: ["diwali", "diya", "festive", "traditional"],
    rating: 4.9,
    review_count: 89,
    sku: "PHA-FES-002",
    weight: "250g",
    materials: ["Premium Felt", "Golden Thread", "Fiber Cotton"],
    colors: ["Festive Mix", "Gold & Red", "Orange & Yellow"],
    customizable: true,
    created_at: "2023-09-15",
  },
  {
    id: "6",
    name: "Felt Star & Moon Keychain",
    slug: "felt-star-moon-keychain",
    description:
      "Adorable hand-stitched star and moon keychains made from premium felt. Each piece is carefully cut, stitched, and stuffed by hand. Available in various color combinations with a sturdy keyring attachment.",
    short_description: "Hand-stitched celestial felt keychain set",
    price: 249,
    compare_price: 349,
    images: [
      "https://images.unsplash.com/photo-1583394293214-4dfabf6a98d6?w=800&q=80",
      "https://images.unsplash.com/photo-1564457374277-1b4a762c7ebf?w=800&q=80",
    ],
    category: categories[5],
    category_id: "6",
    stock: 50,
    is_featured: false,
    is_new: true,
    is_bestseller: true,
    tags: ["keychain", "celestial", "gift", "accessories"],
    rating: 4.6,
    review_count: 112,
    sku: "PHA-ACC-001",
    weight: "30g",
    materials: ["Premium Felt", "Fiber Cotton", "Metal Keyring"],
    colors: ["Pastel Pink", "Sage Green", "Lavender", "Yellow"],
    customizable: true,
    created_at: "2024-01-08",
  },
  {
    id: "7",
    name: "Felt Gift Hamper Box",
    slug: "felt-gift-hamper-box",
    description:
      "A curated collection of handmade felt goodies presented in a beautiful gift box. Includes a felt keychain, a small plushie, a garland, and hand-stitched bookmarks. Perfect for birthdays, baby showers, or any special occasion.",
    short_description: "Curated handmade felt gift hamper",
    price: 1499,
    compare_price: 1999,
    images: [
      "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=800&q=80",
      "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&q=80",
    ],
    category: categories[3],
    category_id: "4",
    stock: 10,
    is_featured: true,
    is_new: false,
    is_bestseller: false,
    tags: ["gift", "hamper", "birthday", "baby shower"],
    rating: 4.9,
    review_count: 28,
    sku: "PHA-GIF-001",
    weight: "500g",
    materials: ["Various Felt Products"],
    colors: ["Pastel Mix", "Custom"],
    customizable: true,
    created_at: "2024-02-14",
  },
  {
    id: "8",
    name: "Felt Elephant Plushie",
    slug: "felt-elephant-plushie",
    description:
      "A lovable hand-stitched elephant plushie crafted from soft premium felt and stuffed with hypoallergenic fiber cotton. Features embroidered details and a cute pompom tail. Perfect for nurseries, children's rooms, or as a thoughtful gift.",
    short_description: "Adorable handmade felt elephant stuffed toy",
    price: 599,
    compare_price: undefined,
    images: [
      "https://images.unsplash.com/photo-1545173168-9f1947eebb7f?w=800&q=80",
      "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=800&q=80",
    ],
    category: categories[0],
    category_id: "1",
    stock: 15,
    is_featured: false,
    is_new: true,
    is_bestseller: false,
    tags: ["elephant", "plushie", "nursery", "children"],
    rating: 4.8,
    review_count: 35,
    sku: "PHA-NUR-002",
    weight: "220g",
    materials: ["Premium Felt", "Hypoallergenic Fiber Cotton"],
    colors: ["Grey & Pink", "Blue & White", "Lavender"],
    customizable: true,
    created_at: "2024-03-12",
  },
  {
    id: "9",
    name: "Felt Wreath — Spring Bloom",
    slug: "felt-wreath-spring-bloom",
    description:
      "A gorgeous hand-stitched felt wreath bursting with spring flowers and greenery. Each flower and leaf is individually crafted and arranged on a sturdy wire base. Measures approximately 35cm in diameter. Perfect for front doors, living rooms, or as a wedding decoration.",
    short_description: "Handmade felt floral wreath for home décor",
    price: 1299,
    compare_price: 1699,
    images: [
      "https://images.unsplash.com/photo-1519378058457-4c29a0a2efac?w=800&q=80",
      "https://images.unsplash.com/photo-1490750967868-88df5691cc3d?w=800&q=80",
    ],
    category: categories[2],
    category_id: "3",
    stock: 6,
    is_featured: true,
    is_new: false,
    is_bestseller: true,
    tags: ["wreath", "spring", "door decor", "flowers"],
    rating: 5.0,
    review_count: 22,
    sku: "PHA-HOM-002",
    weight: "400g",
    dimensions: "35cm diameter",
    materials: ["Premium Felt", "Wire Frame", "Ribbon"],
    colors: ["Spring Mix", "Blush & Ivory", "Wildflower"],
    customizable: false,
    created_at: "2024-02-28",
  },
  {
    id: "10",
    name: "Name Banner — Custom Letters",
    slug: "name-banner-custom-letters",
    description:
      "Personalized hand-stitched felt letter banner — perfect for nurseries, birthdays, or any celebration. Each letter is individually crafted from premium felt, stuffed with fiber cotton, and strung on jute twine. Specify your name or word at checkout.",
    short_description: "Personalized handmade felt name banner",
    price: 799,
    compare_price: undefined,
    images: [
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80",
      "https://images.unsplash.com/photo-1576919228236-a097c32a5cd4?w=800&q=80",
    ],
    category: categories[4],
    category_id: "5",
    stock: 999,
    is_featured: false,
    is_new: true,
    is_bestseller: false,
    tags: ["banner", "personalized", "name", "nursery"],
    rating: 4.9,
    review_count: 56,
    sku: "PHA-WAL-002",
    weight: "Varies",
    materials: ["Premium Felt", "Fiber Cotton", "Jute Twine"],
    colors: ["Blush Pink", "Sage Green", "Mixed Pastels", "Rainbow"],
    customizable: true,
    created_at: "2024-01-20",
  },
  {
    id: "11",
    name: "Felt Bookmark Set",
    slug: "felt-bookmark-set",
    description:
      "A charming set of 4 hand-stitched felt bookmarks in various designs — flowers, stars, animals, and geometric patterns. Each bookmark is made with premium felt and hand-embroidered details. Great for book lovers and as stocking stuffers.",
    short_description: "Set of 4 handmade felt bookmarks",
    price: 349,
    compare_price: 449,
    images: [
      "https://images.unsplash.com/photo-1535016120720-40c646be5580?w=800&q=80",
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80",
    ],
    category: categories[5],
    category_id: "6",
    stock: 40,
    is_featured: false,
    is_new: false,
    is_bestseller: true,
    tags: ["bookmark", "reading", "stationery", "gift"],
    rating: 4.7,
    review_count: 78,
    sku: "PHA-ACC-002",
    weight: "50g",
    materials: ["Premium Felt", "Thread"],
    colors: ["Mixed Pastels", "Earthy Tones"],
    customizable: false,
    created_at: "2023-12-01",
  },
  {
    id: "12",
    name: "Christmas Tree Ornament Set",
    slug: "christmas-tree-ornament-set",
    description:
      "Bring handmade charm to your Christmas tree with this set of 6 hand-stitched felt ornaments. Includes stars, snowflakes, mittens, candy canes, Christmas trees, and gingerbread men. Each ornament features embroidered details and a hanging loop.",
    short_description: "Set of 6 handcrafted felt Christmas ornaments",
    price: 849,
    compare_price: 1099,
    images: [
      "https://images.unsplash.com/photo-1576919228236-a097c32a5cd4?w=800&q=80",
      "https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=800&q=80",
    ],
    category: categories[1],
    category_id: "2",
    stock: 35,
    is_featured: true,
    is_new: false,
    is_bestseller: true,
    tags: ["christmas", "ornaments", "festive", "holiday"],
    rating: 4.8,
    review_count: 94,
    sku: "PHA-FES-003",
    weight: "200g",
    materials: ["Premium Felt", "Fiber Cotton", "Embroidery Thread"],
    colors: ["Traditional Red & Green", "Pastel Winter"],
    customizable: false,
    created_at: "2023-10-01",
  },
  {
    id: "13",
    name: "Felt Celebration Gift Pouch",
    slug: "felt-celebration-gift-pouch",
    description:
      "A charming hand-stitched felt gift pouch filled with cute felt trinkets including a mini plushie and a star keychain. Perfect for small return gifts, birthdays, or festive surprises.",
    short_description: "Handcrafted felt gift pouch with surprise trinkets",
    price: 699,
    compare_price: 899,
    images: [
      "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=800&q=80",
      "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80",
    ],
    category: categories[3],
    category_id: "4",
    stock: 25,
    is_featured: false,
    is_new: true,
    is_bestseller: true,
    tags: ["gift", "pouch", "hamper", "celebration"],
    rating: 4.9,
    review_count: 34,
    sku: "PHA-GIF-002",
    weight: "180g",
    materials: ["Premium Felt", "Cotton Cord"],
    colors: ["Blush Pink", "Sage Green"],
    customizable: true,
    created_at: "2024-02-20",
  },
];

// ─── Reviews ─────────────────────────────────────────────────────────────────
export const testimonials: Review[] = [
  {
    id: "r1",
    product_id: "1",
    user_id: "u1",
    user_name: "Priya Sharma",
    user_avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
    rating: 5,
    comment:
      "Absolutely beautiful quality! The rainbow mobile for my baby's nursery is even more gorgeous in person. The stitching is so perfect and the colors are exactly as shown. Pooja even added a little note with the package — such a personal touch! Will definitely order again.",
    created_at: "2024-03-10",
    verified: true,
  },
  {
    id: "r2",
    product_id: "5",
    user_id: "u2",
    user_name: "Ananya Patel",
    user_avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    rating: 5,
    comment:
      "The Diwali diya set was the most beautiful decoration at our pooja! Everyone kept asking where I got them. The golden embroidery is stunning. Packaging was also very thoughtful — came in a lovely box with tissue paper.",
    created_at: "2024-02-20",
    verified: true,
  },
  {
    id: "r3",
    product_id: "7",
    user_id: "u3",
    user_name: "Sneha Kulkarni",
    user_avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
    rating: 5,
    comment:
      "Ordered the gift hamper for my best friend's baby shower and she was absolutely delighted! The quality of each piece is incredible — you can tell so much love and care goes into every stitch. 100% worth every rupee!",
    created_at: "2024-03-01",
    verified: true,
  },
  {
    id: "r4",
    product_id: "6",
    user_id: "u4",
    user_name: "Meera Reddy",
    user_avatar: "https://images.unsplash.com/photo-1547954575-855750c57bd3?w=100&q=80",
    rating: 5,
    comment:
      "These keychains are SO cute! I ordered for my whole friend group as return gifts for my birthday and everyone loved them. Super quick delivery and they came individually wrapped. Will be ordering more for Diwali gifts!",
    created_at: "2024-02-14",
    verified: true,
  },
  {
    id: "r5",
    product_id: "9",
    user_id: "u5",
    user_name: "Kavya Menon",
    user_avatar: "https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=100&q=80",
    rating: 5,
    comment:
      "The Spring Bloom wreath is absolutely stunning on my front door! The felt flowers look so real and the quality is impeccable. My neighbors always stop to admire it. Pooja was also very responsive when I had questions about customization.",
    created_at: "2024-03-15",
    verified: true,
  },
  {
    id: "r6",
    product_id: "4",
    user_id: "u6",
    user_name: "Ritu Gupta",
    user_avatar: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=100&q=80",
    rating: 4,
    comment:
      "Love the felt cactus plushie — it sits perfectly on my work desk and always makes me smile! The felt is super soft and the stitching is neat. Gave 4 stars only because delivery took a little longer than expected, but the product itself is 5/5.",
    created_at: "2024-01-30",
    verified: true,
  },
];

// ─── Instagram Gallery ────────────────────────────────────────────────────────
export const instagramImages = [
  "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&q=80",
  "https://images.unsplash.com/photo-1490750967868-88df5691cc3d?w=400&q=80",
  "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=400&q=80",
  "https://images.unsplash.com/photo-1576919228236-a097c32a5cd4?w=400&q=80",
  "https://images.unsplash.com/photo-1583394293214-4dfabf6a98d6?w=400&q=80",
  "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=400&q=80",
];

// Helpers
export const getFeaturedProducts = () => products.filter((p) => p.is_featured);
export const getBestSellers = () => products.filter((p) => p.is_bestseller);
export const getNewArrivals = () => products.filter((p) => p.is_new);
export const getProductBySlug = (slug: string) =>
  products.find((p) => p.slug === slug);
export const getProductsByCategory = (categorySlug: string) =>
  products.filter((p) => p.category.slug === categorySlug);
