import { Category, Product, Review } from "@/types";
import { isCategoryMatch } from "@/lib/utils";

// ─── Categories ───────────────────────────────────────────────────────────────
export const categories: Category[] = [
  {
    id: "1",
    name: "Cute Plush Ornaments without Bell",
    slug: "cute-plush-ornaments-without-bell",
    description: "Soft plush felt animals & cute ornaments hand-stitched without bells",
    image: "/images/products/felt-sleeping-bear.jpg",
    product_count: 3,
    color: "bg-brand-pink-light",
  },
  {
    id: "2",
    name: "Cute Plush Ornaments with Bell",
    slug: "cute-plush-ornaments-with-bell",
    description: "Charming plush felt ornaments featuring gentle chiming ghungroo bells",
    image: "/images/products/felt-birds-mobile.jpg",
    product_count: 2,
    color: "bg-brand-lavender",
  },
  {
    id: "3",
    name: "Door and Wall Decor",
    slug: "door-and-wall-decor",
    description: "Whimsical hand-stitched felt branch hangings, torans, and wall art",
    image: "/images/products/owl-branch-hanging.jpg",
    product_count: 4,
    color: "bg-brand-green-light",
  },
  {
    id: "4",
    name: "Festive Special Decor",
    slug: "festive-special-decor",
    description: "Vibrant handcrafted felt Diyas, tassels, torans & festive celebration accents",
    image: "/images/products/diya-hanging-tassels.jpg",
    product_count: 3,
    color: "bg-brand-terracotta-light",
  },
  {
    id: "5",
    name: "Garden Decor",
    slug: "garden-decor",
    description: "Enchanting nature-inspired felt birds, flowers, and outdoor balcony hangings",
    image: "/images/products/diya-hanging-bells.jpg",
    product_count: 2,
    color: "bg-brand-yellow",
  },
  {
    id: "6",
    name: "Personalised Name",
    slug: "personalised-name",
    description: "Handcrafted felt creations with custom names, initials, and personalized colors",
    image: "/images/products/owl-branch-hanging.jpg",
    product_count: 4,
    color: "bg-brand-pink-light",
  },
];

// ─── Products ─────────────────────────────────────────────────────────────────
export const products: Product[] = [
  {
    id: "1",
    name: "Handcrafted Festive Diya Bell Hanging",
    slug: "handcrafted-festive-diya-bell-hanging",
    description:
      "Brighten your home with this exquisite handcrafted felt Diya hanging ornament. Featuring a bright lime-green felt diya base, flame motif, hand-sewn leaf appliques, colorful bead strands, and traditional brass ghungroo bells that create a gentle musical chime. Hand-stitched with love, making it a perfect piece for Diwali, Puja rooms, entrance doors, and festive gifting.",
    short_description: "Vibrant felt Diya ornament with embroidered leaves, beads & brass ghungroo bells",
    price: 499,
    compare_price: 699,
    images: [
      "/images/products/diya-hanging-bells.jpg",
    ],
    category: categories[3],
    category_id: "4",
    stock: 15,
    is_featured: true,
    is_new: true,
    is_bestseller: true,
    tags: ["festive", "diya", "diwali", "puja decor", "handmade", "bells", "toran"],
    rating: 4.9,
    review_count: 28,
    sku: "PHA-FES-001",
    weight: "150g",
    materials: ["Premium Wool Felt", "Wooden & Glass Beads", "Brass Ghungroo Bells", "Embroidery Thread"],
    colors: ["Lime Green & Orange", "Multicolor"],
    customizable: true,
    created_at: "2024-01-15",
  },
  {
    id: "2",
    name: "Royal Magenta Diya Fringe Wall Hanging",
    slug: "royal-magenta-diya-fringe-wall-hanging",
    description:
      "A stunning festive accent crafted from premium magenta felt with delicate stitch work and leaf embroidery. Features a long, lush green tassel fringe accented with cascading brass ghungroo bells that add grace and movement to your doorways, balconies, or living space during auspicious celebrations.",
    short_description: "Elegantly crafted magenta felt Diya with green tassel fringe & cascading brass bells",
    price: 549,
    compare_price: 749,
    images: [
      "/images/products/diya-hanging-tassels.jpg",
    ],
    category: categories[3],
    category_id: "4",
    stock: 12,
    is_featured: true,
    is_new: false,
    is_bestseller: false,
    tags: ["diya", "tassel", "festive decor", "wall hanging", "handmade", "diwali"],
    rating: 4.8,
    review_count: 19,
    sku: "PHA-FES-002",
    weight: "180g",
    materials: ["Premium Wool Felt", "Silk Thread Fringe", "Brass Ghungroo Bells"],
    colors: ["Magenta & Green", "Golden Flame"],
    customizable: true,
    created_at: "2024-01-20",
  },
  {
    id: "3",
    name: "Three Wise Owls Felt Branch Wall Hanging",
    slug: "three-wise-owls-felt-branch-wall-hanging",
    description:
      "Bring warmth and playful charm to your walls with this detailed owl branch hanging. Three adorable felt owls in vibrant pink, blue, and orange hues perch on a soft stuffed green branch detailed with sparkling yellow flowers and trailing beaded strings with chime bells. Each owl is meticulously stitched with button accents and sequin embellishments.",
    short_description: "Handcrafted tree branch featuring 3 colorful embroidered felt owls with yellow flowers & chime bells",
    price: 899,
    compare_price: 1199,
    images: [
      "/images/products/owl-branch-hanging.jpg",
    ],
    category: categories[2],
    category_id: "3",
    stock: 8,
    is_featured: true,
    is_new: true,
    is_bestseller: true,
    tags: ["owl decor", "branch hanging", "wall art", "handmade", "chime bells"],
    rating: 5.0,
    review_count: 34,
    sku: "PHA-WAL-001",
    weight: "250g",
    materials: ["Hand-stitched Wool Felt", "Decorative Buttons & Sequins", "Wooden Beads", "Brass Bells"],
    colors: ["Multicolor Owls", "Forest Green Branch"],
    customizable: true,
    created_at: "2024-02-01",
  },
  {
    id: "4",
    name: "Cozy Paws Felt Sleeping Bear Plush",
    slug: "cozy-paws-felt-sleeping-bear-plush",
    description:
      "Fall in love with this adorable sleeping bear, lovingly hand-stitched with visible contrast blanket embroidery stitches. Crafted from soft cream felt, wearing stylish black overalls with pocket detail and a purple neck scarf. Perfect as a nursery accent, bag charm, tree ornament, or thoughtful handmade gift.",
    short_description: "Hand-stitched felt teddy bear wearing cute black overalls and a purple scarf",
    price: 399,
    compare_price: 499,
    images: [
      "/images/products/felt-sleeping-bear.jpg",
    ],
    category: categories[0],
    category_id: "1",
    stock: 20,
    is_featured: true,
    is_new: false,
    is_bestseller: true,
    tags: ["teddy bear", "nursery ornament", "plush", "handmade", "gift"],
    rating: 4.9,
    review_count: 42,
    sku: "PHA-PLU-001",
    weight: "110g",
    materials: ["Hypoallergenic Wool Felt", "Polyfill Cotton", "Embroidery Floss"],
    colors: ["Cream & Black", "Purple Scarf"],
    customizable: false,
    created_at: "2024-02-10",
  },
  {
    id: "5",
    name: "Enchanted Birds & Branch Hanging Mobile",
    slug: "enchanted-birds-branch-hanging-mobile",
    description:
      "Transform any room into a vibrant paradise with this showstopping felt birds hanging mobile. Features 4 brightly colored songbirds perched atop a hand-sculpted green branch adorned with blossoms, with 6 charming suspended birds swaying gently below. Hand-stitched with vibrant felt art details, making it a dream piece for living rooms, entrance doorways, or baby nurseries.",
    short_description: "Spectacular handcrafted felt mobile with 10 colorful birds perched & suspended on a green branch",
    price: 1299,
    compare_price: 1699,
    images: [
      "/images/products/felt-birds-mobile.jpg",
    ],
    category: categories[1],
    category_id: "2",
    stock: 6,
    is_featured: true,
    is_new: true,
    is_bestseller: true,
    tags: ["bird mobile", "nursery decor", "hanging mobile", "handcrafted art", "statement piece"],
    rating: 5.0,
    review_count: 56,
    sku: "PHA-NUR-001",
    weight: "320g",
    materials: ["Premium Colorfast Felt", "Soft Fiber Fill", "Strong Cotton Cord", "Button Details"],
    colors: ["Multicolor Songbirds", "Deep Green Branch"],
    customizable: true,
    created_at: "2024-02-15",
  },
  {
    id: "6",
    name: "Bloom & Blossom Felt Garden Flower Stick",
    slug: "bloom-blossom-felt-garden-flower-stick",
    description:
      "Charming handcrafted felt flower stick designed to add a bright burst of color to your indoor potted plants, balcony garden, or floral arrangements. Stitched with durable wool felt and mounted on a polished eco-friendly wooden stem.",
    short_description: "Vibrant felt garden flower accent stick for indoor plants and balcony decor",
    price: 349,
    compare_price: 449,
    images: [
      "/images/products/diya-hanging-bells.jpg",
    ],
    category: categories[4],
    category_id: "5",
    stock: 18,
    is_featured: false,
    is_new: true,
    is_bestseller: false,
    tags: ["garden decor", "flower stick", "balcony accent", "handmade decor"],
    rating: 4.8,
    review_count: 14,
    sku: "PHA-GAR-001",
    weight: "90g",
    materials: ["Wool Felt", "Wooden Stake", "Embroidery Floss"],
    colors: ["Pink & Yellow"],
    customizable: true,
    created_at: "2024-02-20",
  },
];

export const testimonials: Review[] = [
  {
    id: "r1",
    product_id: "1",
    user_id: "u1",
    user_name: "Arjun Sharma",
    user_avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&q=80",
    rating: 5,
    comment:
      "Bahut accha product hai. I was initially unsure about ordering handmade décor online, but the quality genuinely impressed me. Stitching is neat, the colours are beautiful and the product feels quite sturdy. Easily washable bhi hai, which is a big plus.",
    created_at: "2024-03-10",
    verified: true,
  },
  {
    id: "r2",
    product_id: "2",
    user_id: "u2",
    user_name: "Karan Mehta",
    user_avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&q=80",
    rating: 5,
    comment:
      "Bought this for my niece’s room and she absolutely loved it. The material feels soft and safe, with no sharp edges or anything that could hurt a child. It looks beautiful and the finishing is very good. Definitely a better choice than plastic décor.",
    created_at: "2024-03-05",
    verified: true,
  },
  {
    id: "r3",
    product_id: "3",
    user_id: "u3",
    user_name: "Simran Kapoor",
    user_avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&q=80",
    rating: 5,
    comment:
      "Halloween décor usually means plastic decorations, so I wanted something different this year. This handmade felt piece looked absolutely adorable and gave our home a cosy festive vibe without looking too over-the-top. It’s lightweight, reusable and easy to clean, so I can bring it out every Halloween. Such a cute and sustainable alternative!",
    created_at: "2024-02-28",
    verified: true,
  },
  {
    id: "r4",
    product_id: "4",
    user_id: "u4",
    user_name: "Kavya Singh",
    user_avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&q=80",
    rating: 5,
    comment:
      "बहुत प्यारा और खूबसूरत handmade décor है। ❤️ Finishing देखकर साफ पता चलता है कि इसे बहुत ध्यान से बनाया गया है। Wash करने के बाद भी इसका shape और colours अच्छे रहे। I really appreciate that it is reusable and made to last instead of being disposable décor.",
    created_at: "2024-02-20",
    verified: true,
  },
  {
    id: "r5",
    product_id: "5",
    user_id: "u5",
    user_name: "Neha Agarwal",
    user_avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&q=80",
    rating: 5,
    comment:
      "I gifted this to my sister for her new home and she absolutely loved it! ❤️ The handmade detailing is beautiful and it makes the room look so warm and elegant. Quality bhi kaafi achhi hai, stitching is strong and the product feels very durable. A perfect handmade gift.",
    created_at: "2024-02-14",
    verified: true,
  },
  {
    id: "r6",
    product_id: "1",
    user_id: "u6",
    user_name: "Riya Mehta",
    user_avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&q=80",
    rating: 5,
    comment:
      "Bahut hi sundar aur neatly made hai! Colours exactly pictures jaise hain. Sabse achhi baat hai ki washable hai, so kids ke room mein use karne mein tension nahi hoti. It feels safe, soft and thoughtfully made. Definitely a beautiful addition to our home.",
    created_at: "2024-02-08",
    verified: true,
  },
  {
    id: "r7",
    product_id: "2",
    user_id: "u7",
    user_name: "Vivek Joshi",
    user_avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&q=80",
    rating: 5,
    comment:
      "A really beautiful piece of sustainable décor. Mujhe sabse achhi baat ye lagi ki it is completely handmade and doesn’t look like typical factory-made decoration. The stitching and finishing are excellent, and being washable makes maintenance very easy. Worth buying!",
    created_at: "2024-01-30",
    verified: true,
  },
  {
    id: "r8",
    product_id: "3",
    user_id: "u8",
    user_name: "Rohan Gupta",
    user_avatar: "",
    rating: 5,
    comment:
      "The product is beautifully made and surprisingly durable. I’ve had it hanging in my living room for months and it still looks as good as new. It adds a very warm and handcrafted feel to the space. Would definitely recommend it for gifting.",
    created_at: "2024-01-25",
    verified: true,
  },
  {
    id: "r9",
    product_id: "4",
    user_id: "u9",
    user_name: "Aditya Kapoor",
    user_avatar: "",
    rating: 5,
    comment:
      "Maine ye Diwali gifting ke liye order kiya tha and everyone appreciated it. The handmade detailing gives it a very premium and personal feel. Plus, it can be reused every year, so it’s much more meaningful than disposable decorations. Great product!",
    created_at: "2024-01-18",
    verified: true,
  },
  {
    id: "r10",
    product_id: "1",
    user_id: "u10",
    user_name: "Ritika Sharma",
    user_avatar: "",
    rating: 5,
    comment:
      "The little felt birds are absolutely beautiful! They added such a cheerful touch to our living room. The stitching is so neat and the colours are lovely. You can really see the handmade craftsmanship.",
    created_at: "2024-01-15",
    verified: true,
  },
  {
    id: "r11",
    product_id: "2",
    user_id: "u11",
    user_name: "Aman Verma",
    user_avatar: "",
    rating: 5,
    comment:
      "Diwali ke liye diya hanging order kiya tha and it looked beautiful in our entrance. The best part is that I can use it every year instead of buying new decorations. Very pretty and reusable.",
    created_at: "2024-01-14",
    verified: true,
  },
  {
    id: "r12",
    product_id: "3",
    user_id: "u12",
    user_name: "Meera Kapoor",
    user_avatar: "",
    rating: 5,
    comment:
      "I bought the garden sticks for my balcony plants and they completely changed the look of the space. Such a simple idea but beautifully executed. They add a very charming handmade touch.",
    created_at: "2024-01-12",
    verified: true,
  },
  {
    id: "r13",
    product_id: "4",
    user_id: "u13",
    user_name: "Nikhil Arora",
    user_avatar: "",
    rating: 5,
    comment:
      "Christmas décor was so cute! 🎄 The little handmade details made our tree look much more personal. Quality is also very good and everything arrived beautifully packed.",
    created_at: "2024-01-10",
    verified: true,
  },
  {
    id: "r14",
    product_id: "5",
    user_id: "u14",
    user_name: "Shreya Gupta",
    user_avatar: "",
    rating: 5,
    comment:
      "Maine nursery ke liye wall hanging liya tha. It looks adorable and the felt is soft and lightweight. Baby ke room ke liye mujhe ye plastic decorations se much better laga.",
    created_at: "2024-01-08",
    verified: true,
  },
  {
    id: "r15",
    product_id: "1",
    user_id: "u15",
    user_name: "Rahul Malhotra",
    user_avatar: "",
    rating: 5,
    comment:
      "Such a beautiful housewarming gift! My friend loved the personalised wall hanging. It felt much more thoughtful than giving another generic home décor item.",
    created_at: "2024-01-05",
    verified: true,
  },
  {
    id: "r16",
    product_id: "2",
    user_id: "u16",
    user_name: "Kavita Joshi",
    user_avatar: "",
    rating: 5,
    comment:
      "The product is even prettier in person. Colours are vibrant, stitching is neat and the whole piece feels very carefully made. It has such a warm handmade character.",
    created_at: "2024-01-03",
    verified: true,
  },
  {
    id: "r17",
    product_id: "3",
    user_id: "u17",
    user_name: "Arjun Mehta",
    user_avatar: "",
    rating: 5,
    comment:
      "Halloween ke liye kuch different chahiye tha, so I ordered this felt décor. It looked adorable and gave the house a cosy festive vibe. Plus, I can reuse it next year!",
    created_at: "2024-01-02",
    verified: true,
  },
  {
    id: "r18",
    product_id: "4",
    user_id: "u18",
    user_name: "Priya Nair",
    user_avatar: "",
    rating: 5,
    comment:
      "I absolutely loved the Rakhi décor. It was colourful without looking too loud and made our festive setup look very elegant. Beautiful handmade work.",
    created_at: "2023-12-28",
    verified: true,
  },
  {
    id: "r19",
    product_id: "5",
    user_id: "u19",
    user_name: "Vivek Sharma",
    user_avatar: "",
    rating: 5,
    comment:
      "Bought these garden sticks for my mother because she loves plants. She was so happy! They look lovely among the greenery and are a really nice way to add some personality to the garden.",
    created_at: "2023-12-25",
    verified: true,
  },
  {
    id: "r20",
    product_id: "1",
    user_id: "u20",
    user_name: "Anjali Patel",
    user_avatar: "",
    rating: 5,
    comment:
      "Ganesh Chaturthi ke liye liya tha and it looked so pretty near our pooja setup. The detailing is amazing and the handmade finish gives it a very authentic feel.",
    created_at: "2023-12-22",
    verified: true,
  },
  {
    id: "r21",
    product_id: "2",
    user_id: "u21",
    user_name: "Karan Mehta",
    user_avatar: "",
    rating: 5,
    comment:
      "The quality genuinely surprised me. The stitching is strong and the product feels durable despite being lightweight. I’ve been using it for months and it still looks great.",
    created_at: "2023-12-20",
    verified: true,
  },
  {
    id: "r22",
    product_id: "3",
    user_id: "u22",
    user_name: "Sneha Kulkarni",
    user_avatar: "",
    rating: 5,
    comment:
      "I gifted this to my sister for her new home and she absolutely loved it. The personalised touch made it feel really special. Beautiful product and lovely packaging.",
    created_at: "2023-12-18",
    verified: true,
  },
  {
    id: "r23",
    product_id: "4",
    user_id: "u23",
    user_name: "Rohan Agarwal",
    user_avatar: "",
    rating: 5,
    comment:
      "Holi décor ke liye perfect tha! Colours were so bright and cheerful. I also liked that it can be stored and reused for future celebrations instead of throwing it away after one season.",
    created_at: "2023-12-15",
    verified: true,
  },
  {
    id: "r24",
    product_id: "5",
    user_id: "u24",
    user_name: "Ishita Singh",
    user_avatar: "",
    rating: 5,
    comment:
      "The little floral hanging looks gorgeous in my bedroom. It’s subtle, colourful and doesn’t make the space look cluttered. Handmade décor really does have a different charm.",
    created_at: "2023-12-12",
    verified: true,
  },
  {
    id: "r25",
    product_id: "1",
    user_id: "u25",
    user_name: "Siddharth Jain",
    user_avatar: "",
    rating: 5,
    comment:
      "I ordered a few pieces for my café and they instantly made the space feel warmer. Customers have actually asked me where I got them from! Very unique compared to regular store-bought décor.",
    created_at: "2023-12-10",
    verified: true,
  },
  {
    id: "r26",
    product_id: "2",
    user_id: "u26",
    user_name: "Neha Bansal",
    user_avatar: "",
    rating: 5,
    comment:
      "Janmashtami ke liye ye hanging liya tha and it looked beautiful near the mandir. Finishing bahut achhi hai and the colours are lovely. Definitely ordering again for other festivals.",
    created_at: "2023-12-08",
    verified: true,
  },
  {
    id: "r27",
    product_id: "3",
    user_id: "u27",
    user_name: "Varun Sethi",
    user_avatar: "",
    rating: 5,
    comment:
      "The best thing about these products is that they don't look mass-produced. Every little stitch and detail makes them feel unique. Really beautiful craftsmanship.",
    created_at: "2023-12-05",
    verified: true,
  },
  {
    id: "r28",
    product_id: "4",
    user_id: "u28",
    user_name: "Pallavi Rao",
    user_avatar: "",
    rating: 5,
    comment:
      "I purchased a personalised name hanging for my daughter’s room. It was so cute and beautifully made. The colours matched the room perfectly and the name detail made it extra special.",
    created_at: "2023-12-02",
    verified: true,
  },
  {
    id: "r29",
    product_id: "5",
    user_id: "u29",
    user_name: "Faizan Khan",
    user_avatar: "",
    rating: 5,
    comment:
      "Eid ke liye ordered some décor pieces and they made our living room look so festive. Packaging was also very thoughtful. I really appreciate products that are handmade and reusable.",
    created_at: "2023-11-28",
    verified: true,
  },
  {
    id: "r30",
    product_id: "1",
    user_id: "u30",
    user_name: "Simran Kaur",
    user_avatar: "",
    rating: 5,
    comment:
      "These are perfect if you want your home to look beautiful without filling it with plastic decorations. The felt pieces are colourful, lightweight and have such a lovely handmade feel.",
    created_at: "2023-11-25",
    verified: true,
  },
  {
    id: "r31",
    product_id: "2",
    user_id: "u31",
    user_name: "Dev Malhotra",
    user_avatar: "",
    rating: 5,
    comment:
      "I bought a few pieces for my balcony and garden. The garden sticks especially are adorable! They add colour among the plants without taking away from the natural look.",
    created_at: "2023-11-22",
    verified: true,
  },
  {
    id: "r32",
    product_id: "3",
    user_id: "u32",
    user_name: "Ayesha Khan",
    user_avatar: "",
    rating: 5,
    comment:
      "Mujhe sabse achhi baat ye lagi ki products washable hain. Kids ke room mein décor rakhna easy ho jata hai because you don't have to worry too much about dust or small stains.",
    created_at: "2023-11-20",
    verified: true,
  },
  {
    id: "r33",
    product_id: "4",
    user_id: "u33",
    user_name: "Anirudh Menon",
    user_avatar: "",
    rating: 5,
    comment:
      "The Onam-themed décor was gorgeous! I was looking for something handmade for our festive setup and this was exactly what I wanted. Simple, elegant and beautifully crafted.",
    created_at: "2023-11-18",
    verified: true,
  },
  {
    id: "r34",
    product_id: "5",
    user_id: "u34",
    user_name: "Divya Shah",
    user_avatar: "",
    rating: 5,
    comment:
      "I ordered this as a return gift for a small family function. Everyone loved how cute and different it was. Much more memorable than the usual gifts you get at events.",
    created_at: "2023-11-15",
    verified: true,
  },
  {
    id: "r35",
    product_id: "1",
    user_id: "u35",
    user_name: "Harsh Vardhan",
    user_avatar: "",
    rating: 5,
    comment:
      "The stitching is incredibly neat. You can tell someone has actually spent time making each piece rather than it coming out of a factory. Really appreciate this kind of craftsmanship.",
    created_at: "2023-11-12",
    verified: true,
  },
  {
    id: "r36",
    product_id: "2",
    user_id: "u36",
    user_name: "Tanvi Mehra",
    user_avatar: "",
    rating: 5,
    comment:
      "Christmas ke time pura house decorate karne ke liye multiple pieces order kiye the. Everything looked so coordinated and colourful. They’re now packed safely for next Christmas too!",
    created_at: "2023-11-10",
    verified: true,
  },
  {
    id: "r37",
    product_id: "3",
    user_id: "u37",
    user_name: "Manish Tiwari",
    user_avatar: "",
    rating: 5,
    comment:
      "I got the garden sticks for my terrace garden and they are my favourite little additions. They make the plants look more lively and cheerful. Very cute gifting option for plant lovers.",
    created_at: "2023-11-08",
    verified: true,
  },
  {
    id: "r38",
    product_id: "4",
    user_id: "u38",
    user_name: "Nandini Iyer",
    user_avatar: "",
    rating: 5,
    comment:
      "The product is soft, lightweight and beautifully finished. I particularly liked that there are no harsh materials or sharp edges, making it suitable for a child’s room.",
    created_at: "2023-11-05",
    verified: true,
  },
  {
    id: "r39",
    product_id: "5",
    user_id: "u39",
    user_name: "Rajiv Khanna",
    user_avatar: "",
    rating: 5,
    comment:
      "Navratri décor was so pretty! The handmade detailing really stood out against our regular decorations. Everyone at home loved it and asked where we bought it from.",
    created_at: "2023-11-02",
    verified: true,
  },
  {
    id: "r40",
    product_id: "1",
    user_id: "u40",
    user_name: "Madhuri Das",
    user_avatar: "",
    rating: 5,
    comment:
      "This is the kind of décor that makes a house feel like home. I placed the hanging near our entryway and it gets compliments from almost everyone who visits.",
    created_at: "2023-10-28",
    verified: true,
  },
  {
    id: "r41",
    product_id: "2",
    user_id: "u41",
    user_name: "Akash Bhatia",
    user_avatar: "",
    rating: 5,
    comment:
      "I wanted an eco-conscious gift for a colleague and found these handmade products. The idea of gifting something reusable and crafted by artisans made it feel much more meaningful.",
    created_at: "2023-10-25",
    verified: true,
  },
  {
    id: "r42",
    product_id: "3",
    user_id: "u42",
    user_name: "Rhea Sood",
    user_avatar: "",
    rating: 5,
    comment:
      "Karwa Chauth ke liye liya tha and it looked gorgeous in our living room. The colours are very elegant and the handmade finish gives it a premium look.",
    created_at: "2023-10-22",
    verified: true,
  },
  {
    id: "r43",
    product_id: "4",
    user_id: "u43",
    user_name: "Gaurav Arora",
    user_avatar: "",
    rating: 5,
    comment:
      "I’ve washed the felt décor once and was happy to see that the shape and colours stayed intact. That makes a big difference for something you plan to keep and reuse for years.",
    created_at: "2023-10-20",
    verified: true,
  },
  {
    id: "r44",
    product_id: "5",
    user_id: "u44",
    user_name: "Pooja Chawla",
    user_avatar: "",
    rating: 5,
    comment:
      "The little animals are so adorable! My kids immediately picked their favourite ones. They’re soft, colourful and beautifully stitched. The room feels much more cheerful now.",
    created_at: "2023-10-18",
    verified: true,
  },
  {
    id: "r45",
    product_id: "1",
    user_id: "u45",
    user_name: "Yash Agarwal",
    user_avatar: "",
    rating: 5,
    comment:
      "Maine ye anniversary gift ke liye personalise karwaya tha. The name detail made it feel genuinely personal and special. Quality bhi excellent hai. Would definitely recommend for gifting.",
    created_at: "2023-10-15",
    verified: true,
  },
  {
    id: "r46",
    product_id: "2",
    user_id: "u46",
    user_name: "Shalini Roy",
    user_avatar: "",
    rating: 5,
    comment:
      "I love how these pieces can work for both festivals and everyday décor. You don't have to pack everything away after one celebration. They look beautiful throughout the year.",
    created_at: "2023-10-12",
    verified: true,
  },
  {
    id: "r47",
    product_id: "3",
    user_id: "u47",
    user_name: "Suresh Krishnan",
    user_avatar: "",
    rating: 5,
    comment:
      "Pongal ke liye ordered a few decorations and they looked beautiful around our entrance. The craftsmanship is lovely and the products feel much more meaningful because they are handmade.",
    created_at: "2023-10-10",
    verified: true,
  },
  {
    id: "r48",
    product_id: "4",
    user_id: "u48",
    user_name: "Ira Kapoor",
    user_avatar: "",
    rating: 5,
    comment:
      "Such a lovely alternative to disposable festive décor. The piece is sturdy, reusable and beautifully made. It has already become part of our annual decoration collection.",
    created_at: "2023-10-08",
    verified: true,
  },
  {
    id: "r49",
    product_id: "5",
    user_id: "u49",
    user_name: "Amit Desai",
    user_avatar: "",
    rating: 5,
    comment:
      "I have ordered from Pooja Handmade Art for different occasions now, Diwali, Christmas and even everyday home décor. Every time the quality has been consistent. Beautiful designs, good finishing and a very special handmade feel.",
    created_at: "2023-10-05",
    verified: true,
  },
];

// ─── Instagram Gallery ────────────────────────────────────────────────────────
export const instagramImages = [
  "/images/insta-1.png",
  "/images/insta-2.png",
  "/images/insta-3.png",
  "/images/insta-4.png",
  "/images/insta-5.png",
  "/images/insta-6.png",
];

// Helpers
export const getFeaturedProducts = () => products.filter((p) => p.is_featured);
export const getBestSellers = () => products.filter((p) => p.is_bestseller);
export const getNewArrivals = () => products.filter((p) => p.is_new);
export const getProductBySlug = (slug: string) =>
  products.find((p) => p.slug === slug);
export const getProductsByCategory = (categorySlug: string) =>
  products.filter((p) => isCategoryMatch(p.category, categorySlug, p.customizable));
